version: "3.9"
services:
  mongodb:
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
  graylog:
    image: graylog/graylog:4.0
    volumes:
      - graylog_data:/usr/share/graylog/data/journal
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9005/
    depends_on:
      - mongodb
      - elasticsearch
    links:
      - mongodb:mongo
      - elasticsearch
    ports:
      - 9005:9000 # Graylog web interface and REST API
      - 1514:1514/udp # Syslog UDP
      - 12202:12201/udp # GELF UDP
    restart: on-failure
volumes:
  mongo_data:
    driver: local
  elasticsearch_data:
    driver: local
  graylog_data:
    driver: local